pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    versionCatalogs {
        libs {
            from(files("gradle/libs.version.toml"))
        }
        plugins {
            from(files("gradle/libs.version.toml"))
        }
        versions {
            from(files("gradle/libs.version.toml"))
        }
    }
}

rootProject.name = 'CrescentSun'
include 'paper'
include 'paper:api'
findProject(':paper:api')?.name = 'api'
include 'paper:impl'
findProject(':paper:impl')?.name = 'impl'

include("paper:api:crescent-core")
findProject(":api:crescent-core")?.name = "crescent-core-api"

include("paper:impl:crescent-core")
findProject(":impl:crescent-core")?.name = "crescent-core-impl"

include 'velocity'