[versions]
# Core
paper-api = "1.21.1-R0.1-SNAPSHOT"

# Crescent Sun plugins
crescent-core = "1.1.0e"
jumpwarps = "1.1.0b"
artifacts = "1.1.0b"
crystals = "1.1.0b"
dropnames = "1.0.0b"

# Other dependencies
triumph-cmd = "2.0.0-SNAPSHOT"
hikari-cp = "5.1.0"
crescentmsg = "1.1.0j"

[libraries]
# Core
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api"}
triumph-cmd = { module = "dev.triumphteam:triumph-cmd-bukkit", version.ref = "triumph-cmd"}
hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari-cp"}
crescentmsg = { module = "it.crescentsun:crescentmsg", version.ref = "crescentmsg"}

# Crescent Sun plugins
crescent-core = { module = "it.crescentsun:crescent-core", version.ref = "crescent-core"}
artifacts = { module = "it.crescentsun:artifacts", version.ref = "artifacts"}

[plugins]
java-library = { id = "java-library"}
maven-publish = {id = "maven-publish"}
shadow = {id = "io.github.goooler.shadow", version = "8.1.8"}